#!/bin/bash
#first launch our new term

while getopts ":e:w:h:x:y:c:" opt; do
  case $opt in
    e) command="$OPTARG"
    ;;
    w) width="$OPTARG"
    ;;
    h) height="$OPTARG"
    ;;
    x) xpos="$OPTARG"
    ;;
    y) ypos="$OPTARG"
    ;;
    c) color="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac

  case $OPTARG in
    -*) echo "Option $opt needs a valid argument"
    exit 1
    ;;
  esac
done

echo $command

#rxvt-unicode -name aterm-ws2 -tr -fn -artwiz-cure-*-*-*-*-11-*-*-*-*-*-*-* -fg yellow -bg [20]$color +sb --depth 32  -e $command &

rxvt-unicode -name aterm-ws2 -tr -fn "xft:Press Start 2P:pixelsize=25" -fg red -bg black +sb --depth 32 -hold -e $command &

# get rxvt PID list

pids=$(pgrep rxvt-unicode)
xpid=$(echo $pids | rev | cut -d ' ' -f 1 | rev)

echo $pids
echo $xpid
sleep 1

while IFS= read line; do
  if [[ "${line}" =~ (0x)([0-9a-z]+)([ ][- ][0-9]+[ ])([0-9]*) ]]; then
    winId="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
    pid="${BASH_REMATCH[4]}"
    echo $xpid
    if [[ "${pid}" -eq "${xpid}" ]]; then
        echo $winId                 
        WIND_IDS+=("${winId}")
    fi
  fi
done < <(wmctrl -lp)


if [ "${#WIND_IDS[@]}" -gt 0 ]; then
  echo "${WIND_IDS[0]}"
fi

remdec ${WIND_IDS[0]}

wmctrl -i -r ${WIND_IDS[0]} -e 0,$xpos,$ypos,$width,$height
